name: Format Code & Build

on:
  push:
    paths:
      - "src/**.js"
      - "**.css"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm install
      - name: Run format
        run: npm run format
      - name: Check code style
        run: npm run format:check
      - name: Commit code format changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit -m "chore: format code"
          fi
      - name: Run ESLint
        run: npm run lint
      - name: Minify JS using UglifyJS
        run: npm run minify
      - name: Commit and push changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit -m "chore: build"
            git push
          fi
